### ISSUE TITLE
Cluster API compatible CLI

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0smotron#129]
Cluster API compatible CLI so that we can do e.g. 
`clusterctl init --infrastructure aws --bootstrap k0smotron`
`clusterctl generate cluster [name] --infrastructure aws --bootstrap k0smotron --kubernetes-version [version] `

**Comment by juanluisvaladas** [comment]
After investigating this, this requires loads of changes and doesn't add much value. We won't implement this, at least not now.

**Comment by juanluisvaladas** [comment]
I managed to get clusterctl working with k0smotron without many changes but it requires renaming our repo and moving loads of files and I don’t think it adds enoguh value for the amount of changes it requires. 

In short due to how providers are configured, we must change the repo name to control-plane-k0smotron, or instead we could keep the repo name and in control-plane-k0smotron have only a bunch of yamls.

The main issue here is that it doesn’t add much value… essentially it allows to:
1-When doing clusterctl init it allows to pass the provider so you don’t need to run kubectl apply -f <install.yaml>
2- clusterctl generate cluster which runs through a yaml template

But those aren’t very valuable IMO:
1- clusterctl init to work requires to pass a clusterctl config file explicitly or to configure the providers list manually, so it doesn’t seem to save any work.
2- clusterctl generate could be useful but most likely the user will end up doing some customization, so the template will fall short anyway
