### ISSUE TITLE
Do we actually need/want `PROJECT` file

### ISSUE THREAD

**Issue by jnummelin** [k0sproject/k0smotron#141]
From @juanluisvaladas :
```
The PROJECT file isn't adding a lot of value and I noticed it's already inconsistent in the main branch (became inconsistent after renaming the Cluster type) so I'm in favour of removing it entirely.
```

We need to make a call whether we want to maintain it or not

**Comment by juanluisvaladas** [comment]
The PROJECT file is only used when using the kubebuilder cli tool. I don't think it can be used now as is.
@jnummelin how did you add the new APIs? Did you use kubebuilder or did you do that manually?

Reasons to keep it:
- Be able to create APIs, webhooks, etc. using the kubebuilder CLI.

Reasons to remove it:
- It's not updated at this time
- Doesn't really add much value since to create a new API you can just instantiate an empty project in an directory, add the API and copy the auto generated code.

I think it's adding any real value at this point and I think it can take new contributors to misunderstandings, however if we keep it, I think we should fix it and have a step in CI verifying it's up to date...

**Comment by jnummelin** [comment]
> how did you add the new APIs? Did you use kubebuilder or did you do that manually?

Manually. I've newer used `PROJECT` file in the past thus did not even think of this "dependency" when creating those bits. 🤦 

Dunno really, for me it's like 50/50 whether to keep it or not.

@makhov WDYT?

**Comment by jnummelin** [comment]
👍 

So let's get rid of it then.

We can always dig it out from archives if needed 😂
