### ISSUE TITLE
Question about etcd and persistence

### ISSUE THREAD

**Issue by franpog859** [k0sproject/k0smotron#812]
What is the difference between `Cluster.spec.etcd` and `Cluster.spec.persistence`? I see that I can configure analogous fields: 
- `Cluster.spec.etcd.autoDeletePVCs`-`Cluster.spec.persistence.autoDeletePVCs`
- `Cluster.spec.etcd.persistence.storageClass`-`Cluster.spec.persistence.persistentVolumeClaim.spec.storageClassName`

The etcd one creates `etcd-data-kmc-...` PVC and the persistence one creates `kmc-...` PVC. By reading the code, I learned that the `kmc` acronym stands for k0smotron cluster. What are these two PVCs used for, especially the `kmc-...` one? The documentation is quite ambiguous

**Comment by makhov** [comment]
Hi! 

`etcd-data-kmc-…` is a PVC created for etcd statefulset.  `kmc-...`  is a PVC created for control plane statefulset. 
Since it's two different PVCs for two different statefulsets both can be configured separately.

The `kmc-…` one was supposed to keep safe all the data that the user might want to store on the control plane side like certificates, [manifests](https://docs.k0sproject.io/stable/manifests/), and so on. But with the latest versions of k0smotron we create and mount certs as secrets, and also have a way to [mount](https://docs.k0smotron.io/stable/resource-reference/#clusterspec) manifests and any other volumes, so `Cluster.spec.persistence` becomes obsolete and even might be deprecated in the future.

**Comment by franpog859** [comment]
Thank you for the answer, @makhov ! Good to know 🎉
